name = "StrategicRandomSearch"
uuid = "69477d89-a91e-4b8d-84f7-32293376f674"
authors = ["Wei HaoShan", "Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.11.0"
Parameters = "0.12.3"
Printf = "1.11.0"
Random = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
